### PR TITLE
feat: add hyperclick provider

### PR DESCRIPTION
**Pull request by Belar**
Adds [Hyperclick](https://atom.io/packages/hyperclick) provider, allowing "go to definition" to be used through `ctrl/cmd + click` combination.

### CODE REVIEW

**Comment by ryanolsonx** [comment]
Thanks for making this!

One thing that we ought to change before we merge this. Do you mind adding hyperclick as a package dependency? When we use `package-dep`, the user is prompted to install it (if they'd like to). Check out the [package.json](https://github.com/atom-ide-community/atom-ide-signature-help/blob/master/package.json#L16) for atom-signature-help. The key pieces are `package-deps` and the npm module `dependency` called [`package-deps`](https://github.com/atom-ide-community/atom-ide-signature-help/blob/master/package.json#L21).

**Comment by vinkla** [comment]
Great pull request!

Since both `hyperclick` and [`atom-ide-ui`](https://github.com/facebookarchive/atom-ide-ui/tree/master/modules/atom-ide-ui/pkg/hyperclick) packages are abandoned, should we maybe fork it under the `atom-ide-community` organisation? Or maybe create a new version of the package?

**Comment by Belar** [comment]
@ryanolsonx Sure thing, done. Thanks for linking example case.

@vinkla Thank you. That's a good question; worth pointing out in the [roadmap discussion](https://github.com/atom-ide-community/atom-ide-community.github.io/issues/3).

**Comment by ryanolsonx** [comment]
@vinkla I think for the short term, we can depend on the abandoned one. It would be great to fork hyperclick but I need to see what it will take to do that (and follow the license).

**Comment by vinkla** [comment]
@ryanolsonx Yeah, using the abandoned one is probably best for the time being. Regarding the license I think we can get by as long as we keep [the original license file](https://github.com/facebookarchive/atom-ide-ui/blob/710f8477607d3788aeadcbdd55079925241ce40d/LICENSE#L1-L30).

**Comment by vinkla** [comment]
Tried running this locally and it works great! Any chance we can move this forward?

**Comment by ryanolsonx** [comment]
Thanks @Belar! 😃

**Pull request merged**
