### PR TITLE
Updated travis badge

### PR DESCRIPTION
**Pull request by vinkla**
Badgen provides better quality badges faster.

### CODE REVIEW

**Comment by ryanolsonx** [comment]
Hey 👋 ! This looks awesome. Thank you for submitting this. By any chance, can you update your commit message to match conventions found here https://www.conventionalcommits.org/en/v1.0.0-beta.3/#summary ? We wouldn't want this commit to trigger a deploy of the package and so a better commit message would be `ci: update travis badge`. I'll document what I'm talking about in a Markdown file for future reference. :) 

Following ☝️ will fix the travis build for this branch.

**Comment by vinkla** [comment]
Done!

**Comment by ryanolsonx** [comment]
Thanks!! 🎉

**Pull request merged**
